language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libopenal-dev libglew-dev libsdl2-dev libconfuse-dev libenet-dev 
 - sudo travis/deps.sh
script: travis/build.sh

