language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcunit1 libcunit1-dev
script: mkdir build && cd build && cmake -DBUILD_TESTS .. && make && make test
