language: c

compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:openmw/deps -y
 - sudo apt-get update -qq
 - if test $CC = gcc; then sudo apt-get install -qq gcc-4.8; fi
 - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
 - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
 - chmod +x travis/deps.sh
 - chmod +x travis/build.sh
 - sudo travis/deps.sh

script: travis/build.sh

notifications:
  email: false
