language: c

sudo: required
dist: trusty

env:
  global:
   - secure: "qvRpkAmV7PRQHoUfjhykb5lkvMyMFAlNYh/1140ej/iHjDsO9bFpX2qxbfgAe8jaW8VBf4ly+VpjA9ByJHWol6/b+FwURa/yiFgNESxeYDUJz/dJCYyrgORH+t41bCwV8SEYZmpa3NJiDi4GkH8iojEi+dQYhWoN4uwEg81m45c="

compiler:
  - gcc
  - clang

before_install: chmod +x travis/*

install: travis/deps.sh

script: travis/make.sh

notifications:
  email: false

addons:
  sonarcloud:
    organization: "openomf"

cache:
  directories:
    - '$HOME/.sonar/cache'
