language: c

dist: xenial

env:
  global:
   - secure: "qvRpkAmV7PRQHoUfjhykb5lkvMyMFAlNYh/1140ej/iHjDsO9bFpX2qxbfgAe8jaW8VBf4ly+VpjA9ByJHWol6/b+FwURa/yiFgNESxeYDUJz/dJCYyrgORH+t41bCwV8SEYZmpa3NJiDi4GkH8iojEi+dQYhWoN4uwEg81m45c="

compiler:
  - gcc

before_install: chmod +x travis/*

script: travis/make.sh

notifications:
  email: false

addons:
  sonarcloud:
    organization: "openomf"
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:zoogie/sdl2-snapshots'
    packages:
      - gcc-8
      - cmake
      - libargtable2-dev
      - libcunit1-dev
      - libopenal-dev
      - libconfuse-dev
      - libenet-dev
      - libsdl2-dev
      - libxmp-dev
      - libpng16-dev

cache:
  directories:
    - '$HOME/.sonar/cache'
