language: c

compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcunit1 libcunit1-dev libsdl2-dev libopenal-dev libconfuse-dev libpng-dev libenet-dev libogg-dev libvorbis-dev
 - if test $CC = gcc; then sudo apt-get install -qq gcc-4.8; fi
 - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
 - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
 - chmod +x travis/build.sh

before_script:
- cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SUBMODULES=On -DUSE_OGGVORBIS=On -DUSE_PNG=On .

notifications:
  email: false
