language: c

compiler:
  - gcc
  - clang
  
before_install:
 - yes | sudo add-apt-repository ppa:openmw/deps
 - sudo apt-get update -qq
 - sudo apt-get install libopenal-dev libglew-dev libsdl2-static-dev libconfuse-dev libenet-dev 
 - sudo travis/deps.sh
 
script: travis/build.sh

notifications:
  email: false
